// export { Index } from './authorizePage/index.ts';
// export { Index } from './registerPage/index.ts';
export { NoPage } from '../pages/404Page/index.ts';
export { ErrorPage } from '../pages/500Page/index.ts';
export { ChatsPage } from '../pages/ChatsPage/index.ts';
export { UserProfilePage } from '../pages/profilePages/showUserInfo/index.ts';
export { ChangeProfilePage } from '../pages/profilePages/changeUserInfo/index.ts';
export { ChangePasswordPage } from '../pages/profilePages/changePassword/index.ts';
export {RegisterPage} from "../pages/registerPage/index.ts";
export {AuthorizePage} from "../pages/authorizePage/index.ts";
export {errorPage} from "../pages/500Page/index.ts";
